### ISSUE TITLE
Generate new word list as basis for dictionary

### ISSUE THREAD

**Issue by lcerrato** [TuftsUniversity/perseids_bodin#2]
Create a new Latin word list and diff against Latinwordlist generated in 2009.
See perseids_bodin/data/ocr/dictionaries_wordlists

**Comment by balmas** [comment]
The source for the updated wordlist is in Gitub, https://github.com/TuftsUniversity/perseids_bodin/commit/137570db599893128a8cd014209e9d227ace327c

**Comment by lcerrato** [comment]
Added this to fbt file. https://github.com/TuftsUniversity/perseids_bodin/commit/425f1fcc42477e064c8a582a4d136ebf047f79e8
